# Generated by Django 5.0.6 on 2024-07-03 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_api.status')),
            ],
        ),
    ]
