# Generated by Django 5.0.6 on 2024-07-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='last_name',
        ),
    ]
