# Generated by Django 5.0.6 on 2024-07-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_remove_todo_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('todo', 'To DO'), ('done', 'Done'), ('in_progress', 'In Progress'), ('archived', 'Archived')], default='todo', max_length=11),
        ),
    ]
